#!/bin/bash

ballerina build airline_reservation_service_distributed.bal
ballerina build car_rental_service_distributed.bal
ballerina build hotel_reservation_service_distributed.bal
ballerina build travel_agency_service_distributed.bal

docker push chanakaudaya/airline_reservation_service_distributed:v6.3
docker push chanakaudaya/car_rental_service_distributed:v6.3
docker push chanakaudaya/hotel_reservation_service_distributed:v6.3
docker push chanakaudaya/travel_agency_service_distributed:v6.3


